//Sign up
export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

///Log in
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

//Log out
export const LOGOUT = 'LOGOUT';

//Get User
export const GET_USER = 'GET_USER';

//Get Filter Lend NTF
export const GET_FILTER_LEND_NFT = 'GET_FILTER_LEND_NFT';
export const GET_FILTER_LEND_NFT_SUCCESS = 'GET_FILTER_LEND_NFT_SUCCESS';
export const GET_FILTER_LEND_NFT_FAIL = 'GET_FILTER_LEND_NFT_FAIL';

// Get Result Lend NTF
export const GET_RESULT_LEND_NFT = 'GET_RESULT_LEND_NFT';
export const GET_RESULT_LEND_NFT_SUCCESS = 'GET_RESULT_LEND_NFT_SUCCESS';
export const GET_RESULT_LEND_NFT_FAIL = 'GET_RESULT_LEND_NFT_FAIL';
