//Sign up
export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

///Log in
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

//Log out
export const LOGOUT = 'LOGOUT';

//Get User
export const GET_USER = 'GET_USER';

// Get Result Borrow
export const GET_RESULT_BORROW = 'GET_RESULT_BORROW';
export const GET_RESULT_BORROW_SUCCESS = 'GET_RESULT_BORROW_SUCCESS';
export const GET_RESULT_BORROW_FAIL = 'GET_RESULT_BORROW_FAIL';

// Get Result Personal Borrow
export const GET_RESULT_PERSONAL_BORROW = 'GET_RESULT_PERSONAL_BORROW';
export const GET_RESULT_PERSONAL_BORROW_SUCCESS =
  'GET_RESULT_PERSONAL_BORROW_SUCCESS';
export const GET_RESULT_PERSONAL_BORROW_FAIL =
  'GET_RESULT_PERSONAL_BORROW_FAIL';

// Get Result Lend Crypto
export const GET_RESULT_LEND_CRYPTO = 'GET_RESULT_LEND_CRYPTO';
export const GET_RESULT_LEND_CRYPTO_SUCCESS = 'GET_RESULT_LEND_CRYPTO_SUCCESS';
export const GET_RESULT_LEND_CRYPTO_FAIL = 'GET_RESULT_LEND_CRYPTO_FAIL';

// Get Result Lend NTF
export const GET_RESULT_LEND_NFT = 'GET_RESULT_LEND_NFT';
export const GET_RESULT_LEND_NFT_SUCCESS = 'GET_RESULT_LEND_NFT_SUCCESS';
export const GET_RESULT_LEND_NFT_FAIL = 'GET_RESULT_LEND_NFT_FAIL';
